### ISSUE TITLE
Can't get this working yet - struggling with including the actual font

### ISSUE THREAD

**Issue by sstorie** [edaquinta/angular-material-icons#1]
I apologize if this is a really dumb question, but I'm trying to leverage this CSS file and host the font myself but can't get the CSS fully working. I've included the following in my CSS right above your code:

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(/assets/fonts/MaterialIcons-Regular.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(/assets/fonts/MaterialIcons-Regular.woff2) format('woff2'),
       url(/assets/fonts/MaterialIcons-Regular.woff) format('woff'),
       url(/assets/fonts/MaterialIcons-Regular.ttf) format('truetype');
}

md-icon > .md-font {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px;  /* Preferred icon size */
    display: inline-block;

...the rest of your CSS...
```
I'm hosting all of these font files on my webserver in the http://server/assets/fonts directory and they're available. One problem I see is the broweser never makes a request to grab these font files. Is there something really obvious I'm doing wrong here?

Thanks for any help you are able to provide.

**Comment by edaquinta** [comment]
Hi, I make this workaround in order to use the material icons, but isn't necessary any more, in version 0.10.0 you can use the icons using the ligatures, just: < md-icon >menu< /md-icon >. You only need to add the Material-ICons fonts on the top
